export default [
    {
        _id: "123",
        firstName: "John",
        lastName: "Cusack",
        age: 20,
        username: "john123",
        password: "123",
        role: "ADMIN",
        likes: 0,
        messageCount: 0,
        tags: {},
        view: "This is the view written by John",

    },
    {
        _id: "234",
        firstName: "Jane",
        lastName: "Tarzan",
        age: 21,
        username: "jane123",
        password: "123",
        role: "REGISTERED",
        likes: 0,
        messageCount: 0,
        tags: {},
        view: "This is my view on the latest new. The drop broke the sustained positive growth trajectory that was seen in the domestic job market since October, showed the data. The month closed with an active jobs count of 270,000 compared with 300,000 in February. March's active jobs count is also 13% lower than a year ago.",
    },
    {
        _id: "345",
        firstName: "Jack",
        lastName: "Skillington",
        age: 22,
        username: "jack123",
        password: "123",
        role: "REGISTERED",
        likes: 0,
        messageCount: 0,
        tags: {},
        view: "GM will take a $1 billion charge in the first quarter, he said. The company had previously projected $1.5 billion in charges related to staff reductions",
    },
];
